# Generated by Django 2.2.9 on 2020-01-17 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fresh', models.IntegerField(choices=[(0, '0점'), (1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')])),
                ('complete', models.IntegerField(choices=[(0, '0점'), (1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')])),
                ('interest', models.IntegerField(choices=[(0, '0점'), (1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')])),
                ('need', models.IntegerField(choices=[(0, '0점'), (1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='투표한 팀')),
                ('description', models.TextField(blank=True)),
                ('user', models.ManyToManyField(through='vote.Relation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='relation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Team'),
        ),
        migrations.AddField(
            model_name='relation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
