# Generated by Django 2.2.9 on 2020-01-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_name',
            field=models.IntegerField(null=True, verbose_name='소속 팀'),
        ),
    ]
